ALTER TABLE mydb.user_has_user_profile DROP FOREIGN KEY fk_USER_has_USER_PROFILE_USER;
ALTER TABLE mydb.user_has_user_profile DROP FOREIGN KEY fk_USER_has_USER_PROFILE_USER_PROFILE1;
ALTER TABLE mydb.status_history DROP FOREIGN KEY fk_status_history_status1;
ALTER TABLE mydb.status_history DROP FOREIGN KEY fk_status_history_request1;
ALTER TABLE mydb.request_user DROP FOREIGN KEY fk_order_user_user1;
ALTER TABLE mydb.request_user DROP FOREIGN KEY fk_request_user_request1;
ALTER TABLE mydb.movement_history DROP FOREIGN KEY fk_movement_history_place1;
ALTER TABLE mydb.movement_history DROP FOREIGN KEY fk_movement_history_request1;
ALTER TABLE mydb.user DROP FOREIGN KEY fk_user_place1;
ALTER TABLE mydb.request DROP FOREIGN KEY fk_order_client1;
DROP TABLE mydb.user_has_user_profile;
DROP TABLE mydb.status_history;
DROP TABLE mydb.request_user;
DROP TABLE mydb.movement_history;
DROP TABLE mydb.user;
DROP TABLE mydb.request;
DROP TABLE mydb.user_profile;
DROP TABLE mydb.status;
DROP TABLE mydb.place;
DROP TABLE mydb.client;